import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { AlertTriangle } from "lucide-react";

export default function DisclaimerPage() {
  return (
    <div className="container mx-auto p-4 max-w-4xl">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-3xl font-bold">Disclaimer</h1>
        <div className="flex gap-2">
          <Link href="/market">
            <Button variant="outline">Market Data</Button>
          </Link>
          <Link href="/">
            <Button variant="outline">Chat</Button>
          </Link>
        </div>
      </div>

      <Card className="p-6 space-y-6">
        <div className="flex items-start gap-3 p-4 bg-yellow-50 dark:bg-yellow-950/20 border border-yellow-200 dark:border-yellow-900 rounded-lg">
          <AlertTriangle className="h-5 w-5 text-yellow-600 dark:text-yellow-500 flex-shrink-0 mt-0.5" />
          <div>
            <h2 className="font-semibold text-yellow-900 dark:text-yellow-100 mb-1">
              Important Notice
            </h2>
            <p className="text-sm text-yellow-800 dark:text-yellow-200">
              This is a demonstration application for educational and development purposes only.
            </p>
          </div>
        </div>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">1. Demo Application</h2>
          <p className="text-muted-foreground">
            TradePal AI is a demonstration application created for educational and development
            purposes. This application is not intended for actual trading, investment decisions, or
            financial advice.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">2. No Financial Advice</h2>
          <p className="text-muted-foreground">
            The information provided by this application, including but not limited to stock quotes,
            options data, market analysis, and AI-generated responses, is for informational
            purposes only. It does not constitute financial, investment, legal, or tax advice. You
            should not rely on this information to make investment decisions.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">3. Market Data Disclaimer</h2>
          <p className="text-muted-foreground">
            Stock prices, options data, and market information displayed in this application are
            provided by third-party data sources and may be delayed, inaccurate, or incomplete. The
            developers of this application do not guarantee the accuracy, completeness, or timeliness
            of any market data. Real-time data may not be available, and prices shown may not reflect
            current market conditions.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">4. Investment Risks</h2>
          <p className="text-muted-foreground">
            Trading stocks, options, and other securities involves substantial risk of loss. Past
            performance is not indicative of future results. You may lose some or all of your
            investment. Options trading involves additional risks and is not suitable for all
            investors. Please consult with a licensed financial advisor before making any investment
            decisions.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">5. No Liability</h2>
          <p className="text-muted-foreground">
            The developers, contributors, and operators of TradePal AI (collectively, "we", "us", or
            "our") shall not be held liable for any losses, damages, or expenses arising from:
          </p>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
            <li>Your use or inability to use this application</li>
            <li>Any errors, inaccuracies, or omissions in the data or information provided</li>
            <li>Any decisions made based on information from this application</li>
            <li>Any financial losses incurred from trading or investment activities</li>
            <li>Technical failures, interruptions, or errors in the application</li>
            <li>Any unauthorized access to your data or information</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">6. AI-Generated Content</h2>
          <p className="text-muted-foreground">
            Responses generated by the AI assistant in this application are created by artificial
            intelligence and may contain errors, inaccuracies, or outdated information. AI-generated
            content should not be relied upon for making financial or investment decisions. Always
            verify information from multiple reliable sources and consult with qualified
            professionals.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">7. Third-Party Services</h2>
          <p className="text-muted-foreground">
            This application may use third-party services and APIs for data and functionality. We
            are not responsible for the availability, accuracy, or terms of service of these
            third-party providers. Your use of third-party services is subject to their respective
            terms and conditions.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">8. No Warranty</h2>
          <p className="text-muted-foreground">
            This application is provided "as is" without any warranties, express or implied,
            including but not limited to warranties of merchantability, fitness for a particular
            purpose, or non-infringement. We do not warrant that the application will be
            uninterrupted, error-free, or secure.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">9. Regulatory Compliance</h2>
          <p className="text-muted-foreground">
            This application is not registered with any financial regulatory authority and is not
            intended to provide regulated financial services. If you require financial services,
            please consult with licensed and registered financial professionals.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">10. Acceptance of Terms</h2>
          <p className="text-muted-foreground">
            By using this application, you acknowledge that you have read, understood, and agree to
            this disclaimer. You understand that this is a demo application and that you use it at
            your own risk. If you do not agree with any part of this disclaimer, you should not use
            this application.
          </p>
        </section>

        <div className="pt-6 border-t">
          <p className="text-sm text-muted-foreground">
            <strong>Last Updated:</strong> {new Date().toLocaleDateString()}
          </p>
          <p className="text-sm text-muted-foreground mt-2">
            If you have any questions about this disclaimer, please contact the development team.
          </p>
        </div>
      </Card>
    </div>
  );
}


